### ISSUE TITLE
Thanks! (not an issue)

### ISSUE THREAD

**Issue by bmbrands** [pjcdawkins/DrooPHP#2]
Please burn after reading..

I just wanted to say thanks for sharing your code for the STV voting system on GitHub. This has helped me get some work done when I got stuck implementing STV for student voting.  I will ask the Github people to add a "Send Github mug as a thank you" button on the issue submission page.

Great stuff!!

**Comment by pjcdawkins** [comment]
You're very welcome... I should say that it's really, really incomplete.

My main problem was that the counting system I was trying to implement (ERS 97) is undocumented except for an incomprehensible description which appears to be based mostly paper counting - http://www.cix.co.uk/~rosenstiel/stvrules/

I imagine simpler STV systems could be implemented much more easily. I'm no longer in this industry... but happy to help.

**Comment by bmbrands** [comment]
Thanks for letting me know. I found that document too and it was giving me headaches. I used your way of  showing voting results which explains how the winners are elected. 
That way if anybody disagrees with the outcome the can still do a manual count and I'd be happy to print out the stvrules for them :)
